version: '3.8'

services:
  riber-digital-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: riber-digital-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Descomenta y configura para enviar emails:
      - RESEND_API_KEY=${RESEND_API_KEY}    
    env_file:
      - .env.production
    networks:
      - proxy        

networks:
  proxy:
    external: true
